baseURL: "https://byatt.io/"
languageCode: "en-us"
title: "byatt.io"
theme: ['papermod']

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "byatt.io"

  defaultTheme: auto

  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowPostBreadCrumbs: true

  menu:
    main:
      - name: CV
        url: cv
        weight: 10

  homeInfoParams:
    Title: byatt.io

  socialIcons:
    - name: linkedin
      title: LinkedIn
      url: "https://linkedin.com/in/wm-byatt"