baseURL: "https://byatt.io/"
languageCode: "en-us"
title: "byatt.io"

params:
  env: production
  description: "byatt.io"

  defaultTheme: auto

  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowPostBreadCrumbs: true

  homeInfoParams:
    Title: byatt.io
    content: Some Content...

  socialIcons:
    - name: linkedin
      title: LinkedIn
      url: "https://linkedin.com/in/wm-byatt"